version: '3.8'
services:
  hardhat_contracts:
    container_name: hardhat_contracts_container
    build: ./docker/hardhat_contracts
    ports:
      - 13040:3000
    volumes:
      - ./hardhat_contracts:/hardhat_contracts
    tty: true
    environment:
      - TZ=Asia/Tokyo
    networks:
      - default

networks:
  default:
